f3basin<-read.table("geo_data/raw/f3basin_utm.txt", sep="\t", col.names=c("EASTING","NORTHING"))
f3basin27<-read.table("geo_data/raw/f3basin_utm27.txt", sep="\t", col.names=c("EASTING","NORTHING"))
basins<-read.table("geo_data/raw/b2_utm.txt", sep="\t", col.names=c("EASTING","NORTHING"))
basins27<-read.table("geo_data/raw/b2_utm27.txt", sep="\t", col.names=c("EASTING","NORTHING"))
saveRDS(f3basin,"geo_data/processed/f3basin.rdata")
saveRDS(f3basin27,"geo_data/processed/f3basin27.rdata")
saveRDS(basins,"geo_data/processed/basins.rdata")
saveRDS(basins27,"geo_data/processed/basins27.rdata")
