f3basin<-read.table("f3basin_utm.txt", sep="\t", col.names=c("UTM_E","UTM_N"))
f3basin27<-read.table("f3basin_utm27.txt", sep="\t", col.names=c("UTM_E","UTM_N"))
basins<-read.table("b2_utm.txt", sep="\t", col.names=c("UTM_E","UTM_N"))
basins27<-read.table("b2_utm27.txt", sep="\t", col.names=c("UTM_E","UTM_N"))
saveRDS(f3basin,"f3basin.rdata")
saveRDS(f3basin27,"f3basin27.rdata")
saveRDS(basins,"basins.rdata")
saveRDS(basins27,"basins27.rdata")
