#Graphs for AGU
require(ggplot2)
#require()


inventory.final<-readRDS("../inventory/inventoryfinal.rdata")
sourceterm<-readRDS("../source_term/tritiumsource.rdata")

comparison<-merge(sourceterm,inventory.final,by.x = "Year", by.y = "MYEAR")
comparison$inventory1bCD<-comparison$inventory1b+comparison$inventoryC

png("test.png", width=720, height=960)
final.plot3<-ggplot(data=inventory.final, aes(x=MYEAR, size=3))
final.plot3<- final.plot3 + theme_bw()
# final.plot3<- final.plot3 +geom_point(aes(y=inventory1), colour='blue', size=2)
final.plot3<- final.plot3 +geom_point(aes(y=inventory1b), colour='red')
# final.plot3<- final.plot3 +geom_point(aes(y=inventory1lm), colour='green', size=2)
final.plot3<- final.plot3 +geom_point(aes(y=t), colour='orange')
#final.plot3<- final.plot3 +geom_point(aes(y=tfl), colour='black')
final.plot3<- final.plot3 +geom_point(aes(y=tC), colour='violet')
final.plot3<- final.plot3 +geom_point(aes(y=tCD), colour='yellow')
final.plot3<- final.plot3 + theme(plot.title=element_text(face="bold", colour="#000000", size=30))
final.plot3<- final.plot3 + theme(axis.title.x = element_text(face="bold", colour="#000000", size=26))
final.plot3<- final.plot3 + theme(axis.title.y = element_text(face="bold", colour="#000000", lineheight=1 , size=26))
final.plot3<- final.plot3 + theme(axis.text.x  = element_text(size=22))
final.plot3<- final.plot3 + theme(axis.text.y  = element_text(size=22))
# final.plot3<- final.plot3 + scale_y_log10()
final.plot3<-final.plot3+labs(title="Tritium Inventory")+xlab("Year")+ylab("Tritium (Ci)")
print(final.plot3)
dev.off()


fp4<-ggplot(data=inventory.final, aes(x=MYEAR,size=3))
fp4<- fp4 +geom_point(aes(y=inventory1), colour='blue')
fp4<- fp4 +geom_point(aes(y=inventory1b), colour='red')
fp4<- fp4 +geom_point(aes(y=inventory1lm), colour='green')
fp4<- fp4 +geom_point(aes(y=t), colour='orange')
# fp4<- fp4 +geom_point(aes(y=tfl), colour='black')
fp4<- fp4 +geom_point(aes(y=tC), colour='violet')
fp4<- fp4 +geom_point(aes(y=tCD), colour='yellow')
fp4<- fp4 + theme(plot.title=element_text(face="bold", colour="#000000", size=30))
fp4<- fp4 + theme(axis.title.x = element_text(face="bold", colour="#000000", size=26))
fp4<- fp4 + theme(axis.title.y = element_text(face="bold", colour="#000000", lineheight=1 , size=26))
fp4<- fp4 + theme(axis.text.x  = element_text(size=22))
fp4<- fp4 + theme(axis.text.y  = element_text(size=22))
fp4<- fp4 + scale_y_log10()
fp4<- fp4 +opts(legend.position = "none")
fp4<-fp4+labs(title="Tritium Inventory")+xlab("Year")+ylab("Tritium (Ci)")
print(fp4)

#png("tritium_comparison.png", width=720, height=960)
png("tritium_comparison2.png", width=960, height=720)
fp5<-ggplot(data=comparison, aes(x=Year,size=6))
fp5<- fp5 + theme_bw()
fp5<- fp5 +geom_point(aes(y=gwInventory), colour='orange', shape=15)
fp5<- fp5 +geom_point(aes(y=inventory1bCD), colour='red', shape=6)
# fp5<- fp5 +geom_point(aes(y=inventory1lm), colour='green')
# fp5<- fp5 +geom_point(aes(y=t), colour='orange')
# fp5<- fp5 +geom_point(aes(y=tfl), colour='black')
# fp5<- fp5 +geom_point(aes(y=tC), colour='violet')
fp5<- fp5 +geom_point(aes(y=tCD), colour='green', shape=8)
fp5<- fp5 + theme(plot.title=element_text(face="bold", colour="#000000", size=30))
fp5<- fp5 + theme(axis.title.x = element_text(face="bold", colour="#000000", size=26))
fp5<- fp5 + theme(axis.title.y = element_text(face="bold", colour="#000000", lineheight=1 , size=26))
fp5<- fp5 + theme(axis.text.x  = element_text(size=22))
fp5<- fp5 + theme(axis.text.y  = element_text(size=22))
fp5<- fp5 + scale_y_log10()
fp5<- fp5 + ylim(1000, 62000)
fp5<- fp5 + theme(legend.position = "none")
fp5<-fp5+labs(title="Tritium Inventory")+xlab("Year")+ylab("Tritium (Ci)")
print(fp5)
dev.off()